# This file generated by Quarto; do not edit by hand.

from __future__ import annotations

from pathlib import Path
from shiny import App, Inputs, Outputs, Session, ui




def server(input: Inputs, output: Outputs, session: Session) -> None:
    import ibis

    import plotly.express as px

    from shiny import ui, render
    from itables import show

    # set plotly express to dark mode
    px.defaults.template = "plotly_dark"

    ibis.options.interactive = True

    t = ibis.examples.penguins.fetch()

    # ========================================================================

    show(t.limit(10).to_pandas())

    # ========================================================================

    show(
      t.group_by(ibis._.species)
      .agg(
        count=ibis._.count()
      )
      .order_by(ibis._["count"].desc())
      .to_pandas()
    )

    # ========================================================================

    ui.input_text("species", "Species:", value="Gentoo")

    # ========================================================================

    @render.plot
    def bar_chart():

        species = input.species()
        #species = "Adelie"

        px.bar(
            t.filter(t.species == species)
            .group_by(ibis._.island)
            .agg(
                count=ibis._.count()
            ),
            x="island",
            y="count",
        )

    # ========================================================================



    return None


_static_assets = ["mre_files","mre_files/libs/quarto-html/tippy.css","mre_files/libs/quarto-html/quarto-syntax-highlighting-dark.css","mre_files/libs/bootstrap/bootstrap-icons.css","mre_files/libs/bootstrap/bootstrap.min.css","mre_files/libs/quarto-dashboard/datatables.min.css","mre_files/libs/clipboard/clipboard.min.js","mre_files/libs/quarto-html/quarto.js","mre_files/libs/quarto-html/popper.min.js","mre_files/libs/quarto-html/tippy.umd.min.js","mre_files/libs/quarto-html/anchor.min.js","mre_files/libs/bootstrap/bootstrap.min.js","mre_files/libs/quarto-dashboard/quarto-dashboard.js","mre_files/libs/quarto-dashboard/stickythead.js","mre_files/libs/quarto-dashboard/datatables.min.js","mre_files/libs/quarto-dashboard/pdfmake.min.js","mre_files/libs/quarto-dashboard/vfs_fonts.js","mre_files/libs/quarto-dashboard/web-components.js","mre_files/libs/quarto-dashboard/components.js"]
_static_assets = {"/" + sa: Path(__file__).parent / sa for sa in _static_assets}

app = App(
    Path(__file__).parent / "mre.html",
    server,
    static_assets=_static_assets,
)
